<?php
use \CodeHelper as CH;
class ModPrivacy extends Module
{
		function __construct() {
$this->title = "Privacy";
$this->titleTooltip = "Privacy";
$pc = (new CH\PageContent(new CH\PaddingContainer(new CH\TextNode("This site uses cookies and Google Analytics. By using this website you agree to this terms of privacy. You are responsible by your own to inform yourself about updates or changes. 'We' means the maintainer of this website. 'You' stands for any user of this website.")),

new CH\PaddingContainer(new CH\H("1","Liability for Content"), new CH\HTMLNode("We make every effort to keep the information on our Web site current, but accept no liability whatsoever for the content provided. Pursuant to &sect;7 par. 1 of TMG (German Tele-Media Act), the law limits our responsibility as a service provider to our own content on these Web pages.
According to &sect;&sect;8 to 10 of TMG, we are not obligated to monitor third party information provided or stored on our Web site. However, we shall promptly remove any content upon becoming aware that it violates the law. Our liability in such an instance shall commence at the time we become aware of the respective violation.")),

new CH\PaddingContainer(new CH\H("1","Liability for Links"), new CH\TextNode("Our site contains links to third-party Web sites. We have no influence whatsoever on the information on these Web sites and accept no guaranty for its correctness. The content of such third-party sites is the responsibility of the respective owners and/or providers.
At the time third-party Web sites were linked to ours, we found NO GROUNDS WHATSOEVER of any likely contravention of the law. We shall promptly delete a link upon becoming aware that it violates the law.")),

new CH\PaddingContainer(new CH\H("1","Copyrights"), new CH\TextNode("The content and works provided on these Web pages are governed by the copyright laws of Germany. Duplication, processing, distribution, or any form of commercialization of such material beyond the scope of the copyright law shall require the prior written consent of its respective author or creator if this content isn't tagged with any special license.")),

new CH\PaddingContainer(new CH\H("1","Data Protection"), new CH\TextNode("Please be aware that there are inherent security risks in transmitting data, such as e-mails, via the Internet, because it is impossible to safeguard completely against unauthorized access by third parties. Nevertheless, we shall safeguard your data, subject to this limitation. In particular, personal information will be transmitted via the Internet only if it does not infringe upon third-party rights, unless the respective party has given its prior consent in view of such security risks. Accordingly, as the Web site provider, we shall not be held liable for any damages incurred as a consequence of such security risks or for any related acts of omission on our part.
We oppose the use of any available contact information by a third party for sending unsolicited advertisements. As the Web site provider, we reserve the express right to take legal action against unsolicited mailing or e-mailing of spam and other similar advertising materials.")),

new CH\PaddingContainer(new CH\H("1","Google Analytics"), new CH\HTMLNode("This website uses Google Analytics, a web analytics service provided by Google, Inc. (&quot;Google&quot;). Google Analytics uses &quot;cookies&quot;, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. In case of activation of the IP anonymization, Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website. Furthermore you can prevent Google's collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under <a href=\"https://tools.google.com/dlpage/gaoptout?hl=en-GB\">Google Analytics Opt-Out Plugin</a>.<br>
Further information concerning the terms and conditions of use and data privacy can be found at <a href=\"http://www.google.com/analytics/terms/gb.html\">Google Analytics Terms</a> or at <a href=\"http://www.google.com/intl/en_uk/analytics/privacyoverview.html\">Analytics Privacy Overview</a>. Please note that on this website, Google Analytics code is supplemented by &quot;gat._anonymizeIp();&quot; to ensure an anonymized collection of IP addresses (so called IP-masking).")),

new CH\PaddingContainer(new CH\H("1","Other"), new CH\TextNode("This website may also use other techniques like cookies to collect data for statistical purposes and for specific functions and features. But we anonimize all this data.")),

new CH\PaddingContainer(new CH\HTMLNode("<i>Sources:</i> 
<ul>
	<li>imressum text: <a href=\"http://www.easy-pix.eu\">Easy-Pix</a>, <a href=\"http://www.twigg.de\">Twigg</a></li>
	<li>google analytics text: <a href=\"http://www.datenschutzbeauftragter-info.de\">datenschutzbeauftragter-info.de</a></li>
</ul>"))));

//$pc = (new CH\PageContent(new CH\IFrame("http://freecraft.servehttp.com:8080/repo2/analytics/index.php?module=CoreAdminHome&action=optOut&language=en", "600px", "400px", new CH\TextNode("Unfortunately your browser doesn't support iframes."))));
$this->content = $pc->printOut();
		}
}
?>
